### ISSUE TITLE
Could support for Ruby 1.8.7 be added please?

### ISSUE THREAD

**Issue by alan-schwarzenberger** [crayfishx/puppet-purge#1]
Hi,
Intending to use this on a shared puppet 3 and 4 system. Assuming this is compatible with Puppet 3 could the compatibility tests for that be switched on please so we know it is?
Many thanks.
Alan

**Comment by crayfishx** [comment]
@alan-schwarzenberger do you mean travis tests?   I enabled testing across Puppet 3 and 4 earlier this week with the 1.0.0 release of the module.... https://travis-ci.org/crayfishx/puppet-purge/builds/149252363

Is this what you meant?

**Comment by alan-schwarzenberger** [comment]
Yes! We found one more Ruby <v2 issue which I suspect a Puppet 3 test would have spotted, although it is trictly a ruby 1.8.7 issue as select! was introduced in a newer ruby version. I can submit a pull request for that, or more simply please could you change line 103 of purge.rb from:
`resource_instances.select!{ |r| purge?(r) }`
to:
`resource_instances = resource_instances.select{ |r| purge?(r) }`
We have tested this and it appears to work correctly for our use cases.

**Comment by alan-schwarzenberger** [comment]
Looks like the same issue as https://github.com/rspec/rspec-core/issues/1864 and the usual solution os to pin rspec to 3.1.0 or to <3.2.0 for testing with Ruby 1.8.x, for example https://github.com/jhoblitt/puppet-mcelog/commit/1355f5136e2c03f12dddf9176ece8c9e6536ccf1

Hope this helps.

**Comment by crayfishx** [comment]
@alan-schwarzenberger It does, thanks - I found the same solution - also discovered that we werent actually testing different versions of puppet....

https://github.com/crayfishx/puppet-purge/commit/398c766936bf856e788da29ad3a601f11cb3a307

oops

If the latest test run succeeds then I'll release a version this afternoon.... thanks for the input.

**Comment by alan-schwarzenberger** [comment]
https://travis-ci.org/crayfishx/puppet-purge/builds/150616344 is looking good. Many thanks @crayfishx

**Comment by crayfishx** [comment]
@alan-schwarzenberger released on the forge as 1.0.1

**Comment by alan-schwarzenberger** [comment]
Perfect. Many thanks.
